const APP_KEY='eduArenaV3';
const state=JSON.parse(localStorage.getItem(APP_KEY)||'null')||{name:'زائر',xp:0,level:1,played:0,correct:0,answered:0,streak:0,bestStreak:0,scores:[],achievements:[],categoryStats:{},lastQuiz:null};
function save(){localStorage.setItem(APP_KEY,JSON.stringify(state))}
function levelFor(xp){return Math.floor(xp/500)+1}
function refresh(){state.level=levelFor(state.xp);save()}
function qs(s){return document.querySelector(s)}
function toast(msg){const t=qs('#toast');if(!t)return;t.textContent=msg;t.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>t.style.display='none',2400)}
function esc(x){return String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setUser(){const n=localStorage.getItem('eduArenaName');if(n)state.name=n;refresh()}
function navActive(){const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===p))}
function shell(){setUser();navActive();document.querySelectorAll('[data-name]').forEach(e=>e.textContent=state.name);document.querySelectorAll('[data-level]').forEach(e=>e.textContent=state.level);document.querySelectorAll('[data-xp]').forEach(e=>e.textContent=state.xp)}
function startQuiz(cat='all',count=15){localStorage.setItem('quizConfig',JSON.stringify({cat,count}));location.href='quiz.html'}
function makeCategories(){return ['القانون والرقابة','المعرفة العامة','اللغة والمهارات','التحديات المختلطة']}
function classify(q){const t=q.q+' '+(q.explanation||'');if(/الرقابة|الجهاز|مالية|المحاسب|التفتيش/.test(t))return 'القانون والرقابة';if(/الهمزة|إملاء|لغة|نحو|كلمة/.test(t))return 'اللغة والمهارات';if(/ثقافة|تاريخ|جغرافيا|علوم|عاصمة/.test(t))return 'المعرفة العامة';return 'التحديات المختلطة'}
function decorateQuestions(){return rawQuestions.map((q,i)=>({...q,id:i+1,category:classify(q),difficulty:i%5===0?'خبير':i%3===0?'متقدم':'مبتدئ'}))}
function renderDashboard(){shell();const p=qs('#dash');if(!p)return;const accuracy=state.answered?Math.round(state.correct/state.answered*100):0;p.innerHTML=`<div class="grid"><section class="hero card"><div class="eyebrow">EDU ARENA • منصة التحدي الذكي</div><h1 class="title">مرحباً ${esc(state.name)} 👋</h1><p class="sub">اختر تحدياً، اجمع XP، ابنِ سلسلة انتصارات ونافس على لوحة الصدارة.</p><div class="actions"><button class="btn" onclick="startQuiz('all',15)">ابدأ تحدياً سريعاً</button><a class="btn alt" href="categories.html">استكشف المجالات</a></div></section><section class="stats"><div class="stat">XP<b>${state.xp}</b></div><div class="stat">المستوى<b>${state.level}</b></div><div class="stat">الدقة<b>${accuracy}%</b></div><div class="stat">أفضل سلسلة<b>${state.bestStreak}</b></div></section>${makeCategories().map((c,i)=>`<article class="card category span3"><div><div class="icon">${['⚖️','🧠','🔤','🔥'][i]}</div><h3>${c}</h3><p class="sub">تحديات متدرجة مع شرح فوري.</p></div><button class="btn alt" onclick="startQuiz('${c}',10)">ابدأ</button></article>`).join('')}<section class="card span8"><div class="section-title">رحلة المستوى</div><p class="sub">${state.xp%500} / 500 XP للمستوى التالي</p><div class="progress"><i style="width:${state.xp%500/5}%"></i></div></section><section class="card span4"><div class="section-title">إنجازاتك</div><div class="list"><div class="row">🏆 أول تحدٍ <b>${state.played>=1?'✓':'—'}</b></div><div class="row">🔥 سلسلة 5 <b>${state.bestStreak>=5?'✓':'—'}</b></div></div></section></div>`}
function renderCategories(){shell();const p=qs('#categories');if(!p)return;p.innerHTML=`<div class="top"><div><div class="eyebrow">المكتبة التفاعلية</div><h1 class="title">مجالات المسابقة</h1><p class="sub">اختر مجالاً أو ادخل التحدي المختلط.</p></div></div><div class="grid">${makeCategories().map((c,i)=>`<article class="card span6"><div class="icon">${['⚖️','🧠','🔤','🔥'][i]}</div><h2>${c}</h2><p class="sub">أسئلة مختارة من بنك الأسئلة مع مستويات صعوبة متعددة.</p><button class="btn" onclick="startQuiz('${c}',15)">دخول المجال</button></article>`).join('')}</div>`}
function renderLeaderboard(){shell();const p=qs('#leaderboard');if(!p)return;let rows=[{name:state.name,xp:state.xp,score:Math.max(...state.scores,0)}, {name:'بطل المنصة',xp:4200,score:96},{name:'المتحدي الذهبي',xp:3650,score:92},{name:'صانع المعرفة',xp:3100,score:89}].sort((a,b)=>b.xp-a.xp);p.innerHTML=`<div class="card"><div class="eyebrow">المنافسة</div><h1 class="title">لوحة الصدارة</h1><p class="sub">هذه النسخة تعمل محلياً على الجهاز. الربط العالمي الحقيقي يحتاج Backend وحسابات ومزامنة.</p><table class="table"><thead><tr><th>#</th><th>المتسابق</th><th>XP</th><th>آخر نتيجة</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td>${r.xp}</td><td>${r.score}%</td></tr>`).join('')}</tbody></table></div>`}
function renderProfile(){shell();const p=qs('#profile');if(!p)return;p.innerHTML=`<div class="grid"><section class="card span6"><div class="avatar">${esc(state.name[0]||'م')}</div><h1>${esc(state.name)}</h1><p class="sub">المستوى ${state.level} • ${state.xp} XP</p><div class="field"><label>اسم العرض</label><input id="newName" value="${esc(state.name)}"></div><button class="btn" onclick="saveProfile()">حفظ الملف</button></section><section class="card span6"><h2>إحصاءات الحساب</h2><div class="list"><div class="row">المسابقات <b>${state.played}</b></div><div class="row">الإجابات الصحيحة <b>${state.correct}</b></div><div class="row">أفضل سلسلة <b>${state.bestStreak}</b></div></div></section></div>`}
function saveProfile(){const n=qs('#newName').value.trim();if(n){state.name=n;localStorage.setItem('eduArenaName',n);save();toast('تم حفظ الملف');renderProfile()}}
function renderAchievements(){shell();const p=qs('#achievements');if(!p)return;const items=[['🌱','البداية','أكمل أول مسابقة',state.played>=1],['🔥','متوهج','حقق سلسلة من 5 إجابات صحيحة',state.bestStreak>=5],['🎯','قناص','تجاوز دقة 90%',state.answered>0&&state.correct/state.answered>=.9],['🚀','صاعد','وصل إلى المستوى 5',state.level>=5]];p.innerHTML=`<div class="card"><h1 class="title">قاعة الإنجازات</h1><div class="grid">${items.map(x=>`<div class="card span6"><div class="icon">${x[0]}</div><h2>${x[1]}</h2><p class="sub">${x[2]}</p><span class="badge">${x[3]?'مكتمل':'قيد التحدي'}</span></div>`).join('')}</div></div>`}
function renderSettings(){shell();const p=qs('#settings');if(!p)return;p.innerHTML=`<div class="card"><h1 class="title">الإعدادات</h1><div class="field"><label>عدد الأسئلة في التحدي السريع</label><select id="defaultCount"><option>10</option><option selected>15</option><option>20</option><option>30</option></select></div><button class="btn alt" onclick="localStorage.removeItem(APP_KEY);location.href='index.html'">تصفير بيانات هذا الجهاز</button></div>`}
window.startQuiz=startQuiz;window.saveProfile=saveProfile;
document.addEventListener('DOMContentLoaded',()=>{const page=document.body.dataset.page;if(page==='dashboard')renderDashboard();if(page==='categories')renderCategories();if(page==='leaderboard')renderLeaderboard();if(page==='profile')renderProfile();if(page==='achievements')renderAchievements();if(page==='settings')renderSettings()});
