let qsData=[],i=0,score=0,streak=0,seconds=20,timer=null,answered=false,startedAt=0,config={cat:'all',count:15};
const $=s=>document.querySelector(s);const shuffle=a=>a.slice().sort(()=>Math.random()-.5);const escQ=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function eligible(){return rawQuestions.map((q,n)=>({...q,id:n+1,category:classifyLocal(q),difficulty:n%5===0?'خبير':n%3===0?'متقدم':'مبتدئ'}))}
function classifyLocal(q){const t=q.q+' '+(q.explanation||'');if(/الرقابة|الجهاز|مالية|المحاسب|التفتيش/.test(t))return 'القانون والرقابة';if(/الهمزة|إملاء|لغة|نحو|كلمة/.test(t))return 'اللغة والمهارات';if(/ثقافة|تاريخ|جغرافيا|علوم|عاصمة/.test(t))return 'المعرفة العامة';return 'التحديات المختلطة'}
function boot(){const saved=JSON.parse(localStorage.getItem('quizConfig')||'null');if(saved)config=saved;let pool=eligible();if(config.cat!=='all')pool=pool.filter(q=>q.category===config.cat);if(!pool.length)pool=eligible();qsData=shuffle(pool).slice(0,Math.min(config.count||15,pool.length));render();}
function render(){const q=qsData[i];$('#counter').textContent=`${i+1} / ${qsData.length}`;$('#score').textContent=score;$('#streak').textContent=streak;$('#difficulty').textContent=q.difficulty;$('#question').textContent=q.q;$('#feedback').style.display='none';$('#feedback').innerHTML='';answered=false;startedAt=Date.now();seconds=20;updateTimer();clearInterval(timer);timer=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timer);if(!answered)answer(-1)}} ,1000);$('#options').innerHTML=shuffle(q.options.map((x,idx)=>({x,idx}))).map(o=>`<button class="option" data-idx="${o.idx}">${escQ(o.x)}</button>`).join('');document.querySelectorAll('.option').forEach(b=>b.onclick=()=>answer(+b.dataset.idx))}
function updateTimer(){$('#timer').textContent=`00:${String(seconds).padStart(2,'0')}`;$('#timer').classList.toggle('urgent',seconds<=5)}
function answer(idx){if(answered)return;answered=true;clearInterval(timer);const q=qsData[i],ok=idx===q.correct;const elapsed=(Date.now()-startedAt)/1000;document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(+b.dataset.idx===q.correct)b.classList.add('correct');if(+b.dataset.idx===idx&&!ok)b.classList.add('wrong')});let gain=ok?100:0;if(ok&&elapsed<=7)gain+=50;if(ok){streak++;score+=gain}else streak=0;$('#score').textContent=score;$('#streak').textContent=streak;const fb=$('#feedback');fb.style.display='block';fb.innerHTML=`<b>${ok?'إجابة صحيحة 🎉':'ليست صحيحة'}</b><p>${escQ(q.explanation||'لا يوجد شرح إضافي.')}</p><button class="btn" onclick="next()">${i===qsData.length-1?'إنهاء المسابقة':'السؤال التالي'}</button>`;}
function next(){i++;if(i>=qsData.length)return finish();render()}
function finish(){const st=JSON.parse(localStorage.getItem(APP_KEY)||'null')||state;st.played=(st.played||0)+1;st.answered=(st.answered||0)+qsData.length;// session correct count is tracked separately in finishData
st.correct=(st.correct||0)+(window.sessionCorrect||0);st.bestStreak=Math.max(st.bestStreak||0,window.sessionBest||0);st.xp=(st.xp||0)+score;st.level=levelFor(st.xp);st.scores=st.scores||[];st.scores.push(Math.round((window.sessionCorrect||0)/qsData.length*100));save();location.href='results.html?score='+score+'&correct='+(window.sessionCorrect||0)+'&total='+qsData.length+'&xp='+st.xp}
window.sessionCorrect=0;window.sessionBest=0;const _answer=answer;answer=function(idx){const before=answered;_answer(idx);if(!before&&answered&&idx===qsData[i].correct){window.sessionCorrect++;window.sessionBest=Math.max(window.sessionBest,streak)}};
window.next=next;boot();
